name: CI

on: [push]

jobs:
  test:
    name: CI
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: setup npm registry
        run: |
          npm config set registry https://jfrog.hub.vwgroup.com/artifactory/api/npm/remote-npm-public/
          npm config set _auth ${{ secrets.ARTIFACTORY_NPM_TOKEN }}
      - name: ci
        run: |
          yarn install
          yarn ci
